[package]
name = "cookietyper"
version = "0.1.0"
edition = "2024"

[dependencies]
cookietyper-core = { path = "../cookietyper-core" }
flume = "0.11.1"
lingual-number = { path = "../lingual-number/" }
